name: CD

on:
  push:
    branches: ['release-7.1-keyspace']
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-arm64:
    name: Build ARM64 Image
    runs-on: arm64
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Build and Push Images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: "linux/arm64"
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          tags: hub.pingcap.net/sunxiaoguang/serverless/pd:${{ github.sha }}-arm64
  build-amd64:
    name: Build AMD64 Image
    runs-on: amd64
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_ACTION_BOT }}
    steps:
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Build and Push Images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: "linux/amd64"
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          build-args: |
            GITHUB_TOKEN=${{ secrets.GIT_ACTION_BOT }}
          tags: hub.pingcap.net/sunxiaoguang/serverless/pd:${{ github.sha }}-amd64
  multi-arch:
    name: Create Multi-Architecture Image
    runs-on: amd64
    needs: ["build-arm64", "build-amd64"]
    steps:
      - name: create-manifest
        run: |
          docker manifest create hub.pingcap.net/sunxiaoguang/serverless/pd:${{ github.sha }} \
          --amend hub.pingcap.net/sunxiaoguang/serverless/pd:${{ github.sha }}-amd64 \
          --amend hub.pingcap.net/sunxiaoguang/serverless/pd:${{ github.sha }}-arm64
      - name: push-manifest
        run: |
          docker manifest push hub.pingcap.net/sunxiaoguang/serverless/pd:${{ github.sha }}
      - name: set-additional-tags
        if: ${{ github.ref == 'refs/heads/release-7.1-keyspace' && github.event_name == 'push' }}
        run: |
          # Remove the local manifest entry if it exists
          docker manifest rm hub.pingcap.net/keyspace/pd:v7.1.0 || true
          
          docker manifest create hub.pingcap.net/keyspace/pd:v7.1.0 \
          --amend hub.pingcap.net/sunxiaoguang/serverless/pd:${{ github.sha }}-amd64 \
          --amend hub.pingcap.net/sunxiaoguang/serverless/pd:${{ github.sha }}-arm64
          
          docker manifest push hub.pingcap.net/keyspace/pd:v7.1.0
