name: TSO Function Test
on:
  push:
    branches:
      - release-7.1-keyspace
  pull_request:
    branches:
      - release-7.1-keyspace
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  tso-function-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make TSO Function Test
        run: make test-tso-function
