name: TSO Consistency Test
on:
  # Only run when the new code is merged into master.
  push:
    branches:
      - release-7.1-keyspace
  pull_request:
    branches:
      - release-7.1-keyspace
jobs:
  tso-consistency-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20.1"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Make TSO Consistency Test
        run: make test-tso-consistency
